-- Create images table for storing image metadata
CREATE TABLE IF NOT EXISTS public.images (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    url TEXT NOT NULL,
    category TEXT NOT NULL,
    description TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Enable RLS
ALTER TABLE public.images ENABLE ROW LEVEL SECURITY;

-- Allow public read access
CREATE POLICY "Allow public read" ON public.images FOR SELECT USING (true);

-- Allow authenticated inserts
CREATE POLICY "Allow authenticated inserts" ON public.images FOR INSERT WITH CHECK (auth.role() = 'authenticated');

-- Allow authenticated updates
CREATE POLICY "Allow authenticated updates" ON public.images FOR UPDATE USING (auth.role() = 'authenticated');

-- Insert sample images (replace URLs with actual Supabase Storage URLs after uploading)
INSERT INTO public.images (name, url, category, description) VALUES
    ('hero-bg', 'https://your-project.supabase.co/storage/v1/object/public/images/hero-bg.jpg', 'hero', 'Hero background image'),
    ('chuka-portrait', 'https://your-project.supabase.co/storage/v1/object/public/images/chuka-portrait.jpg', 'about', 'Chuka portrait'),
    ('book-love-lasts', 'https://your-project.supabase.co/storage/v1/object/public/images/book-love-lasts.png', 'books', 'The Love That Lasts book cover'),
    ('book-spiritual', 'https://your-project.supabase.co/storage/v1/object/public/images/book-spiritual.jpg', 'books', 'Spiritual Nuggets to Nurture book cover'),
    ('book-make-work', 'https://your-project.supabase.co/storage/v1/object/public/images/book-make-work.jpg', 'books', 'Lets Make it Work book cover')
ON CONFLICT (name) DO NOTHING;
